services:
  - type: web
    name: search-service
    env: node
    buildCommand: cd server/services/search-service && npm install
    startCommand: cd server/services/search-service && npm start
    envVars:
      - key: PORT
        value: 3003
      - key: MONGO_URI
        value: mongodb+srv://hatim:mecatech@cluster0.urne9v5.mongodb.net/Mecano
      - key: FRONTEND_URL
        value: https://frontend-service.onrender.com
    plan: free
    autoDeploy: true

  - type: web
    name: auth-service
    env: node
    buildCommand: cd server/services/auth-service && npm install
    startCommand: cd server/services/auth-service && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://arazzak2002:uPtejgtGR7C1Ujzn@cluster0.urne9v5.mongodb.net/Auth
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: GOOGLE_CLIENT_ID
        value: 961029157972-u1snijjdd7vpdqverlns8oiuj17f374d.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: EMAIL_USER
        value: a.razzak2002@gmail.com
      - key: EMAIL_PASS
        value: rsfv ifzm yjfi kgpu
      - key: CLIENT_URL
        value: https://frontend-service.onrender.com
    plan: free
    autoDeploy: true

  - type: web
    name: client-service
    env: node
    buildCommand: cd server/services/client_service && npm install
    startCommand: cd server/services/client_service && npm start
    envVars:
      - key: PORT
        value: 5007
      - key: MONGO_URI
        value: mongodb+srv://arazzak2002:uPtejgtGR7C1Ujzn@cluster0.urne9v5.mongodb.net/client
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: AUTH_SERVICE_URL
        value: https://auth-service.onrender.com/api/users/me
    plan: free
    autoDeploy: true

  - type: web
    name: mecanique-service
    env: node
    buildCommand: cd server/services/mecanique_service && npm install
    startCommand: cd server/services/mecanique_service && npm start
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://hatim:mecatech@cluster0.urne9v5.mongodb.net/Mecano
    plan: free
    autoDeploy: true

  - type: web
    name: rendez-vous-service
    env: node
    buildCommand: cd server/services/rendez-vous-service && npm install
    startCommand: cd server/services/rendez-vous-service && npm start
    envVars:
      - key: PORT
        value: 3007
      - key: MONGO_URI
        value: mongodb+srv://hatim:mecatech@cluster0.urne9v5.mongodb.net/rendez-vous
      - key: SEARCH_SERVICE_URL
        value: https://search-service.onrender.com
    plan: free
    autoDeploy: true

  - type: web
    name: frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npx serve -s dist -l 5173
    envVars:
      - key: REACT_APP_SEARCH_SERVICE_URL
        value: https://search-service.onrender.com
      - key: REACT_APP_AUTH_SERVICE_URL
        value: https://auth-service.onrender.com
      - key: REACT_APP_CLIENT_SERVICE_URL
        value: https://client-service.onrender.com
      - key: REACT_APP_MECANIQUE_SERVICE_URL
        value: https://mecanique-service.onrender.com
      - key: REACT_APP_RENDEZ_VOUS_SERVICE_URL
        value: https://rendez-vous-service.onrender.com
      - key: NODE_VERSION
        value: 18.16.1
    plan: free
    autoDeploy: true